---
- name: Compliance Check Phase
  hosts: all
  gather_facts: true
  vars:
    repo_url: "git@github.com:nerani22/BEL.git"
    dest_path: "/tmp/BEL"
    commit_msg: "Generating & commiting remediation"

  tasks:
    - name: Format the date
      set_fact:
       currentdate_: "{{ '%d_%m_%Y' | strftime(ansible_date_time.epoch) }}"

    - name: Run SCAP compliance scan
      ##command: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_anssi_bp28_minimal \
               #--results /tmp/results.xml --report /tmp/report.html \
               #/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      command: oscap xccdf generate fix --fix-type ansible --profile ospp --output "/tmp/ospp-remediations_{{currentdate_}}.yml" /tmp/results.xml
      register: compliance_check
      failed_when: false

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: key
        mode: '0600'
        delegate_to: localhost
    
    - name: Specifying a path directly
      ansible.builtin.fetch:
        src: /tmp/ospp-remediations_{{currentdate_}}.yml
        dest: /tmp/BEL
        flat: yes

    - name: Clone Git repository with SSH key
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_path }}"
        version: main
        accept_hostkey: yes
        key_file: "key"
        update: yes
      delegate_to: localhost

    - name: Configure Git username
      ansible.builtin.command: git config user.name "ansible-bot"
      args:
        chdir: "{{ dest_path }}"
      delegate_to: localhost

    - name: Configure Git email
      ansible.builtin.command: git config user.email "nrathi@redhat.com"
      args:
        chdir: "{{ dest_path }}"
      delegate_to: localhost

    - name: Stage the modified file
      ansible.builtin.command: git add .
      args:
        chdir: "{{ dest_path }}"
      delegate_to: localhost

    - name: Commit the changes
      ansible.builtin.command: git commit -m "{{ commit_msg }}"
      args:
        chdir: "{{ dest_path }}"
      register: commit_result
      failed_when: commit_result.rc != 0 and "'nothing to commit'" not in commit_result.stderr
      delegate_to: localhost

    - name: Push changes back to Git repo
      ansible.builtin.command: git push origin main
      args:
        chdir: "{{ dest_path }}"
      delegate_to: localhost