---
- name: Check compliance with SCAP
  hosts: all
  become: true
  tasks:
    - name: Run OpenSCAP scan
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_standard
        --results /tmp/results.xml
        --report /tmp/report.html
        /usr/share/xml/scap/ssg-rhel8-ds.xml
      register: scan

    - name: Parse result count
      shell: grep 'result="fail"' /tmp/results.xml | wc -l
      register: failed_rules
      changed_when: false

    - name: Set fact if non-compliant
      set_fact:
        is_non_compliant: "{{ failed_rules.stdout|int > 0 }}"
