---
- name: RHEL 9 to 10 Upgrade - Phase 1 (Pre-upgrade)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    leapp_report_dir: "/var/lib/leapp"
    leapp_artifacts_dir: "/etc/leapp/files"
    RHEL_9_ISO: "/tmp/rhel-9.6-x86_64-dvd.iso"
    mount_path: /mnt/rhel9

  tasks:
    - name: Ensure Leapp is installed
      package:
        name:
          - leapp
          - leapp-repository
          - leapp-upgrade
        state: present

    - name: Create mount point for ISO
      file:
        path: "{{ mount_path }}"
        state: directory

    - name: Mount RHEL 9 ISO
      mount:
        path: "{{ mount_path }}"
        src: "{{ RHEL_9_ISO }}"
        fstype: iso9660
        opts: loop
        state: mounted

    - name: Prepopulate Leapp answerfile
      copy:
        dest: /var/lib/leapp/answerfile
        content: |
          [remove_pam_pkcs11_module_check]
          confirm = True

    - name: Run Leapp pre-upgrade using ISO
      command: >
        leapp preupgrade --no-rhsm --iso {{ RHEL_9_ISO }}
      register: preupgrade_output
      failed_when: "'FAIL' in preupgrade_output.stderr"
      #ignore_errors: yes

    - name: Check if pre-upgrade passed
      debug:
        var: preupgrade_output.stdout_lines
    
    #- name: Install Leapp packages online server
    #  dnf:
    #    name:
    #      - leapp
    #      - leapp-upgrade
    #    state: present

    #- name: Copy required upgrade data (custom answers, if any)
    #  copy:
    #    src: files/answerfile
    #    dest: "{{ leapp_artifacts_dir }}/answerfile"
    #    mode: 0644

    #- name: Run pre-upgrade check
    #  command: leapp preupgrade
    #  register: preupgrade_result
    #  failed_when: "'FAIL' in preupgrade_result.stderr"

    #- name: Parse Leapp report and fail if issues found
    #  shell: |
    #    grep -i 'inhibitor' {{ leapp_report_dir }}/leapp-report.txt || true
    #  register: inhibitors
    #  failed_when: inhibitors.stdout != ""

    - name: Notify pre-upgrade passed
      debug:
        msg: "Pre-upgrade passed, ready for upgrade to RHEL 10."
