---
- name: Compliance Check Phase
  hosts: all
  gather_facts: true
  tasks:
    - name: Configure static IP
      nmcli:
        conn_name: "{{ ansible_interfaces | reject('equalto', 'lo') | list | first }}"
        ifname: "{{ ansible_interfaces | reject('equalto', 'lo') | list | first }}"
        type: ethernet
        ip4: "192.168.64.50/24"
        gw4: "192.168.64.1"
        state: present

    - name: Bring connection up
      command: nmcli con up "{{ ansible_interfaces | reject('equalto', 'lo') | list | first }}"
      

      
