---
- name: RHEL 8.10 to 9.6 Upgrade - Phase 1 (Pre-upgrade)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    #leapp_report_dir: "/var/lib/leapp"
    #leapp_artifacts_dir: "/etc/leapp/files"
    RHEL_9_ISO: "/opt/repos/rhel-9.6-x86_64-dvd.iso"
    #mount_path: /mnt/rhel8

  tasks:
    - name: Ensure Leapp is installed
      ansible.builtin.package:
        name:
          - leapp
          - leapp-repository
          - leapp-upgrade
        state: present
      become: yes

    - name: Remove unsupported AllowZoneDrifting in firewalld
      lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: '^AllowZoneDrifting='
        state: absent
      notify: Restart firewalld
      become: yes

    - name: Allow root login for SSH temporarily (if disabled)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
      notify: Restart sshd
      become: yes

    - name: Prepopulate Leapp answerfile
      ansible.builtin.copy:
        dest: /var/log/leapp/answerfile
        content: |
          [check_vdo]
          confirm = True
      become: yes

    - name: Run Leapp pre-upgrade using ISO
      ansible.builtin.command: >
        leapp preupgrade --no-rhsm --iso {{ RHEL_9_ISO }}
      register: preupgrade_output
      failed_when: "'FAIL' in preupgrade_output.stderr"
      become: yes
      #ignore_errors: yes

    - name: Check if pre-upgrade passed
      ansible.builtin.debug:
        var: preupgrade_output.stdout_lines

    - name: Notify pre-upgrade passed
      ansible.builtin.debug:
        msg: "Pre-upgrade passed, ready for upgrade to RHEL 9.x."

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
