---
- name: Upgrade - Phase 2 (Execute Upgrade)
  hosts: all
  become: yes

  vars:
    leapp_report_dir: "/var/lib/leapp"
    leapp_artifacts_dir: "/etc/leapp/files"
    RHEL_8_ISO: "/opt/repos/rhel-8.6-x86_64-dvd.iso"
    #mount_path: /mnt/rhel9
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

  tasks:
    - name: Run Leapp upgrade using ISO
      ansible.builtin.command: >
        leapp upgrade --no-rhsm --iso {{ RHEL_8_ISO }}
      register: upgrade_output
      failed_when: "'FAIL' in upgrade_output.stderr"
      become: yes
      #ignore_errors: yes

    - name: Show upgrade output
      ansible.builtin.debug:
        var: upgrade_output.stdout_lines      

    #- name: Run the upgrade online
    #  command: leapp upgrade
    #  register: upgrade_result
    #  failed_when: "'FAIL' in upgrade_result.stderr"

    - name: Reboot system for upgrade
      ansible.builtin.reboot:
        reboot_timeout: 1800
      ignore_unreachable: true
        #test_command: "rpm -qf /etc/redhat-release"

  handlers:
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
      become: yes

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: yes
