---
- name: Upgrade - Phase 2 (Execute Upgrade)
  hosts: all
  become: yes

  vars:
    leapp_report_dir: "/var/log/leapp"
    leapp_artifacts_dir: "/etc/leapp/files"
    RHEL_9_ISO: "/home/neha/rhel-9.6-x86_64-dvd.iso"
    mount_path: /mnt/rhel9

  tasks:
    - name: Run Leapp upgrade using ISO
      command: >
        leapp upgrade --no-rhsm --iso {{ RHEL_9_ISO }}
      register: upgrade_output
      failed_when: "'FAIL' in upgrade_output.stderr"
      become: yes
      #ignore_errors: yes
      
    - name: Show upgrade output
      debug:
        var: upgrade_output.stdout_lines
      
    #- name: Run the upgrade online
    #  command: leapp upgrade
    #  register: upgrade_result
    #  failed_when: "'FAIL' in upgrade_result.stderr"

    - name: Reboot system for upgrade
      reboot:
        reboot_timeout: 900
        #test_command: "rpm -qf /etc/redhat-release"

  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
      become: yes

    - name: Restart sshd
      service:
        name: sshd
        state: restarted
      become: yes
